version: '2'
services:
# https://www.elastic.co/guide/en/beats/metricbeat/current/running-in-container.html#monitoring-host
  metricbeat:
    build: .
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    network_mode: host
